[package]
name = "sourcestats"
version = "0.1.0"
authors = ["Dreae <dreae@dreae.onl>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["diesel_postgres_pool", "serve", "tera_templates"]