[package]
name = "sourcestats_protocol"
version = "0.1.0"
authors = ["Dreae <dreae@dreae.onl>"]
edition = "2018"
build = "build.rs"

[dependencies]
capnp = "0.9.4"
ring = "0.14.2"
bytes = "0.4.11"
byteorder = "1.3.1"

[build-dependencies]
capnpc = "0.9.3"