[package]
name = "sourcestats_daemon"
version = "0.1.0"
authors = ["Dreae <dreae@dreae.onl>"]
edition = "2018"
build = "build.rs"

[dependencies]
capnp = "0.9.4"
ring = "0.14.2"
mio = "0.6.16"

[build-dependencies]
capnpc = "0.9.3"